logger:
  level: "debug"
  file: "log.txt"


storage:
  type: sql
  driver: pgx
  dsn: "postgres://postgres:postgres@localhost:5432/calendar"

http:
  host: 127.0.0.1
  port: 1111

grpc:
  host: 127.0.0.1
  port: 50051